//
// Fully synthetic MeasurementRun/VolumeComparisonRecord fixtures for the
// public STAGING demo build (VITE_CAMPO_DEMO=true — see api.ts). Every
// numeric value, path, and identifier here is fabricated for this slice; none
// of it is derived from a real client measurement. See
// docs/adr/ADR-008-hosted-demo-data-v1.md.
import type { MeasurementRun, VolumeComparisonRecord } from './api'

const DEMO_SHA_1 = 'deadbeef'.repeat(8)
const DEMO_SHA_2 = 'c0ffee00'.repeat(8)
const DEMO_SHA_3 = '0bad0bad'.repeat(8)

const RUN_1_COMPLETED: MeasurementRun = {
  schema_version: '1',
  run_id: 'demo-run-001',
  source_path: 'demo/pila-01-madera-nativa.laz',
  source_sha256: DEMO_SHA_1,
  status: 'completed',
  readiness: {
    stage: 'reference_validated',
    pipeline_completed: true,
    observable_geometry_ready: true,
    physical_face_area_ready: true,
    geometric_volume_ready: true,
    reference_validated: true,
    blocker_codes: [],
  },
  started_at: '2026-08-10T14:05:00Z',
  completed_at: '2026-08-10T14:22:30Z',
  code_version: 'demo-fixture-v1',
  coordinate_metadata: {
    crs_wkt: null,
    crs_epsg: 32719,
    crs_source: 'demo-fixture',
    is_explicit: true,
    vertical_datum: null,
    horizontal_units: 'metre',
  },
  timber_stack: {
    localization_mode: 'demo-fixture',
    point_count_input: 482000,
    point_count_selected: 391500,
    selected_fraction: 0.8123,
    detected_components: 1,
    longitudinal_coverage: 0.94,
    vertical_extent_fraction: 0.88,
    transverse_extent_fraction: 0.91,
    parameters: {},
  },
  front_cross_section: {
    longitudinal_span: 8.4,
    median_height: 2.15,
    maximum_height: 2.6,
    rectangle_area: 18.06,
    trapezoid_area: 16.42,
    valid_bin_fraction: 0.97,
    parameters: {},
  },
  projected_face_raster: {
    area_source_units_squared: 16.42,
    cell_size_u: 0.05,
    cell_size_z: 0.05,
    raster_rows: 52,
    raster_cols: 168,
    u_min: 0,
    u_max: 8.4,
    z_min: 0,
    z_max: 2.6,
    projected_point_count: 391500,
    raw_occupied_cell_count: 6584,
    denoised_occupied_cell_count: 6420,
    retained_component_cell_count: 6420,
    filled_cell_count: 6570,
    component_count: 1,
    scanline_disagreement_fraction: 0.012,
    parameters: {},
  },
  front_depth: {
    front_side: 'near',
    cell_size_u: 0.05,
    cell_size_z: 0.05,
    raster_rows: 52,
    raster_cols: 168,
    u_min: 0,
    u_max: 8.4,
    z_min: 0,
    z_max: 2.6,
    projected_point_count: 391500,
    valid_cell_count: 6420,
    surface_scale_u: 1,
    surface_scale_z: 1,
    recession_threshold_source_units: 0.08,
    candidate_count: 3,
    front_depth_runtime_seconds: 1.24,
    recession_runtime_seconds: 0.87,
    regions: [
      {
        rank: 1,
        cell_count: 320,
        area_source_units_squared: 0.8,
        median_recession_source_units: 0.11,
        max_recession_source_units: 0.19,
        recession_score_source_units_cubed: 0.088,
        u_min: 3.1,
        u_max: 3.9,
        z_min: 0.4,
        z_max: 1.1,
        u_centroid: 3.5,
        z_centroid: 0.75,
      },
    ],
    parameters: {},
  },
  face_area_comparison: {
    estimate_method: 'projected_face_raster',
    estimate_value: 16.42,
    estimate_unit: 'square_metres',
    reference: {
      label: 'Medición de referencia (demo)',
      value: 16.0,
      unit: 'square_metres',
      method: 'cinta métrica (demo)',
      source: 'demo-fixture',
      same_pile_confirmed: true,
      notes: 'Valor de referencia sintético.',
    },
    comparison_ready: true,
    blocker_codes: [],
    signed_error: 0.42,
    absolute_error: 0.42,
    relative_error: 0.02625,
    absolute_relative_error: 0.02625,
    percent_error: 2.625,
    absolute_percent_error: 2.625,
  },
  log_detection: { method: 'demo-fixture', candidate_count: 46, parameters: {} },
  results: [
    {
      method: 'convex_hull',
      volume: 34.2,
      volume_unit: 'm3',
      point_count_input: 482000,
      point_count_used: 391500,
      parameters: {},
      warnings: [],
      runtime_seconds: 0.42,
      provenance: { source: 'demo-fixture' },
    },
    {
      method: 'alpha_shape',
      volume: 31.8,
      volume_unit: 'm3',
      point_count_input: 482000,
      point_count_used: 391500,
      parameters: { alpha: 0.15 },
      warnings: [],
      runtime_seconds: 0.91,
      provenance: { source: 'demo-fixture' },
    },
  ],
  reference: {
    label: 'Medición de referencia (demo)',
    value: 32.5,
    unit: 'm3',
    method: 'cubicación manual (demo)',
    recorded_at: '2026-08-10T09:00:00Z',
    notes: 'Valor de referencia sintético para fines de demostración.',
  },
  warnings: [],
  artifacts: [],
  provenance: { source: 'demo-fixture', generated_for: 'hosted-demo-data-v1' },
  notes: 'Registro de demostración (datos sintéticos). No corresponde a un cliente real.',
}

const RUN_2_PARTIAL: MeasurementRun = {
  schema_version: '1',
  run_id: 'demo-run-002',
  source_path: 'demo/pila-02-en-proceso.laz',
  source_sha256: DEMO_SHA_2,
  status: 'completed',
  readiness: {
    stage: 'physical_face_area',
    pipeline_completed: true,
    observable_geometry_ready: true,
    physical_face_area_ready: true,
    geometric_volume_ready: false,
    reference_validated: false,
    blocker_codes: ['insufficient_point_density'],
  },
  started_at: '2026-08-14T09:12:00Z',
  completed_at: '2026-08-14T09:19:45Z',
  code_version: 'demo-fixture-v1',
  coordinate_metadata: {
    crs_wkt: null,
    crs_epsg: 32719,
    crs_source: 'demo-fixture',
    is_explicit: true,
    vertical_datum: null,
    horizontal_units: 'metre',
  },
  timber_stack: {
    localization_mode: 'demo-fixture',
    point_count_input: 210500,
    point_count_selected: 152300,
    selected_fraction: 0.7235,
    detected_components: 2,
    longitudinal_coverage: 0.81,
    vertical_extent_fraction: 0.76,
    transverse_extent_fraction: 0.79,
    parameters: {},
  },
  front_cross_section: {
    longitudinal_span: 6.1,
    median_height: 1.85,
    maximum_height: 2.2,
    rectangle_area: 11.29,
    trapezoid_area: 10.05,
    valid_bin_fraction: 0.89,
    parameters: {},
  },
  projected_face_raster: {
    area_source_units_squared: 10.05,
    cell_size_u: 0.05,
    cell_size_z: 0.05,
    raster_rows: 44,
    raster_cols: 122,
    u_min: 0,
    u_max: 6.1,
    z_min: 0,
    z_max: 2.2,
    projected_point_count: 152300,
    raw_occupied_cell_count: 4310,
    denoised_occupied_cell_count: 4102,
    retained_component_cell_count: 3890,
    filled_cell_count: 4050,
    component_count: 2,
    scanline_disagreement_fraction: 0.031,
    parameters: {},
  },
  front_depth: null,
  face_area_comparison: null,
  log_detection: null,
  results: [],
  reference: null,
  warnings: [
    {
      code: 'insufficient_point_density',
      severity: 'blocker',
      message:
        'Densidad de puntos insuficiente para estimar el volumen geométrico de forma confiable.',
    },
    {
      code: 'partial_occlusion',
      severity: 'warning',
      message: 'Posible oclusión parcial en el extremo derecho de la pila.',
    },
  ],
  artifacts: [],
  provenance: { source: 'demo-fixture', generated_for: 'hosted-demo-data-v1' },
  notes:
    'Registro de demostración (datos sintéticos). Etapa intermedia: bloqueado antes del volumen geométrico.',
}

const RUN_3_FAILED: MeasurementRun = {
  schema_version: '1',
  run_id: 'demo-run-003',
  source_path: 'demo/pila-03-fallida.laz',
  source_sha256: DEMO_SHA_3,
  status: 'failed',
  readiness: {
    stage: 'not_ready',
    pipeline_completed: false,
    observable_geometry_ready: false,
    physical_face_area_ready: false,
    geometric_volume_ready: false,
    reference_validated: false,
    blocker_codes: ['localization_failed'],
  },
  started_at: '2026-08-18T11:00:00Z',
  completed_at: '2026-08-18T11:02:10Z',
  code_version: 'demo-fixture-v1',
  coordinate_metadata: null,
  timber_stack: null,
  front_cross_section: null,
  projected_face_raster: null,
  front_depth: null,
  face_area_comparison: null,
  log_detection: null,
  results: [],
  reference: null,
  warnings: [
    {
      code: 'localization_failed',
      severity: 'blocker',
      message: 'No fue posible localizar automáticamente la pila de madera en la nube de puntos.',
    },
  ],
  artifacts: [],
  provenance: { source: 'demo-fixture', generated_for: 'hosted-demo-data-v1' },
  notes:
    'Registro de demostración (datos sintéticos). Ejecución fallida: localización automática no logró converger.',
}

export const DEMO_RUNS: MeasurementRun[] = [RUN_1_COMPLETED, RUN_2_PARTIAL, RUN_3_FAILED]

export const DEMO_COMPARISONS: Record<string, VolumeComparisonRecord[]> = {
  'demo-run-001': [
    {
      schema_version: '1',
      comparison_id: 'demo-comparison-001',
      run_id: 'demo-run-001',
      estimate_result_index: 0,
      comparison: {
        estimate_method: 'convex_hull',
        estimate_value: 34.2,
        reference: RUN_1_COMPLETED.reference!,
        unit: 'm3',
        signed_error: 1.7,
        absolute_error: 1.7,
        relative_error: 0.0523,
        absolute_relative_error: 0.0523,
        percent_error: 5.23,
        absolute_percent_error: 5.23,
      },
      created_at: '2026-08-10T14:22:31Z',
    },
  ],
}
